from __future__ import annotations

import sys
from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected exactly one match, found {count}: {old[:140]!r}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")


def patch_compiler() -> None:
    replace_once(
        "src/contextcanon/compiler.py",
        "import hashlib\nfrom pathlib import Path\n",
        "import hashlib\nimport posixpath\nfrom pathlib import Path\n",
    )

    replace_once(
        "src/contextcanon/compiler.py",
        "The copy is intentional: it makes the Official Context Package self-contained, so the package can later be published or consumed without needing the original authoring repository layout. In a standalone package the original source path may no longer exist; the materialized copy is what preserves the reviewed resource bytes.\n\n`contextcanon build` refreshes generated package files.",
        "The copy is intentional: it makes the Official Context Package self-contained, so the package can later be published or consumed without needing the original authoring repository layout. In a standalone package the original source path may no longer exist; the materialized copy is what preserves the reviewed resource bytes.\n\nWhen an exact Markdown Resource links back to its owning Node's generated `CONTEXT.md`, ContextCanon materializes a tiny generated bridge at that linked location instead of copying whatever generated output happened to be on disk. The bridge points to this package's top-level Official Context. This keeps the Resource's exact bytes and link shape usable without making package identity depend on a previous build.\n\n`contextcanon build` refreshes generated package files.",
    )

    p = Path("src/contextcanon/compiler.py")
    text = p.read_text(encoding="utf-8")
    anchor = '''    @staticmethod\n    def _resource_namespace(node_id: str) -> str:\n        if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,63}", node_id):\n            return node_id\n        return "sha256-" + hashlib.sha256(node_id.encode("utf-8")).hexdigest()\n\n'''
    helper = '''    @staticmethod\n    def _resource_namespace(node_id: str) -> str:\n        if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,63}", node_id):\n            return node_id\n        return "sha256-" + hashlib.sha256(node_id.encode("utf-8")).hexdigest()\n\n    def _is_generated_context_target(self, source: Path) -> bool:\n        if source.name != "CONTEXT.md":\n            return False\n        node_root = source.parent.resolve()\n        return (node_root / "CONTEXT.src.md").is_file() or node_root in self._source_overrides\n\n    @staticmethod\n    def _context_bridge_bytes(published: str) -> bytes:\n        target = posixpath.relpath("CONTEXT.md", start=posixpath.dirname(published))\n        return (\n            "# ContextCanon Official Context bridge\\n\\n"\n            "> [!NOTE]\\n"\n            "> **GENERATED BRIDGE — DO NOT EDIT.**\\n"\n            "> An exact Topic Resource linked to its owning Node's generated `CONTEXT.md` before materialization.\\n"\n            f"> Continue at [this package's Official Context]({target}).\\n"\n        ).encode("utf-8")\n\n'''
    if anchor not in text:
        raise SystemExit("compiler resource namespace anchor missing")
    text = text.replace(anchor, helper, 1)

    start = text.index("    def _resource_closure(")
    end = text.index("\n    def _compile_local_topics(", start)
    closure = '''    def _resource_closure(self, seed: Path, node_name: str, topic_id: str, locator: str) -> list[Path]:\n        self._validate_resource(seed, node_name, topic_id, locator)\n        if self._is_generated_context_target(seed):\n            raise ContextCanonError(\n                f"{node_name} Topic {topic_id}: generated CONTEXT.md is a Context Node target, not an authored Resource: {locator}"\n            )\n        queue = [seed.resolve()]\n        visited: set[Path] = set()\n        result: list[Path] = []\n        while queue:\n            source = queue.pop(0).resolve()\n            if source in visited:\n                continue\n            visited.add(source)\n            result.append(source)\n            if self._is_generated_context_target(source):\n                # The linked generated surface is represented by a deterministic\n                # package-local bridge. Never read previous generated bytes.\n                continue\n            content = self._file_overrides.get(source, source.read_bytes())\n            if source.suffix.lower() != ".md":\n                continue\n            text = content.decode("utf-8")\n            rel = source.relative_to(self.repo_root).as_posix()\n            for linked_locator in local_markdown_targets(text):\n                linked = (source.parent / linked_locator).resolve()\n                if linked.is_dir():\n                    continue\n                if self._is_generated_context_target(linked):\n                    if linked not in visited:\n                        queue.append(linked)\n                    continue\n                self._validate_resource(linked, node_name, f"closure:{rel}", linked_locator)\n                if linked not in visited:\n                    queue.append(linked)\n        return result\n'''
    text = text[:start] + closure + text[end:]

    old = '''                        content = self._file_overrides.get(source, source.read_bytes())\n                        previous = resources.get(published)\n'''
    new = '''                        content = (\n                            self._context_bridge_bytes(published)\n                            if self._is_generated_context_target(source)\n                            else self._file_overrides.get(source, source.read_bytes())\n                        )\n                        previous = resources.get(published)\n'''
    if text.count(old) != 1:
        raise SystemExit(f"compiler local resource content anchor count {text.count(old)}")
    text = text.replace(old, new, 1)
    p.write_text(text, encoding="utf-8")


def patch_tests() -> None:
    p = Path("tests/test_context_folder_orientation.py")
    text = p.read_text(encoding="utf-8")
    old_import = "from contextcanon.compiler import CONTEXT_FOLDER_README, Compiler\n"
    new_import = old_import + "from contextcanon.outputs import check_outputs, write_outputs\n"
    if old_import not in text:
        raise SystemExit("context-folder import anchor missing")
    text = text.replace(old_import, new_import, 1)

    marker = "    def test_resource_free_node_stays_without_context_directory_material(self):\n"
    test = '''    def test_resource_link_to_generated_context_is_independent_of_previous_build(self):\n        root = self.make_repo(with_resource=True)\n        (root / "guide.md").write_text(\n            "# Guide\\n\\nSee [Project Context](CONTEXT.md).\\n",\n            encoding="utf-8",\n        )\n\n        # Reproduce the real ai-workstation compiler-0.4 shape: a stale generated\n        # Official Context exists and its resource tree even contains a copied\n        # CONTEXT.src.md. Neither may influence the new package identity.\n        (root / "CONTEXT.md").write_text("stale generated context\\n", encoding="utf-8")\n        legacy = root / "CONTEXT" / "references"\n        legacy.mkdir(parents=True)\n        (legacy / "CONTEXT.src.md").write_bytes((root / "CONTEXT.src.md").read_bytes())\n\n        first = Compiler(root).compile(root)\n        bridge = "CONTEXT/references/demo-node/CONTEXT.md"\n        self.assertIn(bridge, first.resources)\n        self.assertIn("Official Context bridge", first.resources[bridge].decode("utf-8"))\n        self.assertIn("../../../CONTEXT.md", first.resources[bridge].decode("utf-8"))\n        self.assertNotIn(b"stale generated context", first.resources[bridge])\n        self.assertNotIn("CONTEXT/references/demo-node/CONTEXT.src.md", first.resources)\n\n        write_outputs(first)\n        self.assertFalse((legacy / "CONTEXT.src.md").exists())\n\n        second = Compiler(root).compile(root)\n        self.assertEqual(first.package_digest, second.package_digest)\n        self.assertEqual(first.resources, second.resources)\n        self.assertEqual(check_outputs(second), [])\n\n'''
    if marker not in text:
        raise SystemExit("context-folder test insertion marker missing")
    p.write_text(text.replace(marker, test + marker, 1), encoding="utf-8")


def patch_plan() -> None:
    p = Path("PLAN.md")
    text = p.read_text(encoding="utf-8")
    anchor = "##### Deferred compatibility debt\n"
    block = '''##### S — Real machine-state upgrade hardening\n\nGoal: use the project owner's current published `ai-workstation` machine state as an upgrade boundary, while keeping every repair generic enough to protect future ContextCanon projects.\n\n**Status: ACTIVE — step 2 of 4.**\n\n- [x] 1. Derive a compact regression from the current nine authored `ai-workstation` Nodes and prove the exact eight accepted Parent edges plus sibling isolation.\n- [ ] 2. Remove package identity feedback from old generated Resource links such as `SECURITY.md -> CONTEXT.md`; previous generated output must never affect a fresh compile.\n- [ ] 3. Provide a safe explicit recovery/re-adoption path for a reusable owner Source whose legacy onboarding choice is no longer present in machine state, without replaying the already accepted placement review.\n- [ ] 4. Prove the combined real upgrade shape end-to-end: pre-Parent/pre-Source machine state -> recovered Development Workflow Source at the intended ancestor -> exact Parent chain -> offline scoped descendant context.\n\nReal-state evidence: the supplied machine snapshot has nine accepted placement Nodes whose `CONTEXT.src.md` hashes exactly match `placement-acceptance.json`; it has no accepted Sources or `.context/sources` store. Its compiler-0.4 root output also contains a generated `CONTEXT/references/CONTEXT.src.md`, and the acceptance-recorded root package digest differs from the package digest written by the same Step-9 journal while the normalized digest and authoring-source hash agree. This makes generated-Resource feedback and lost owner-Source recovery concrete upgrade defects rather than hypothetical debt.\n\n'''
    if anchor not in text:
        raise SystemExit("PLAN deferred debt anchor missing")
    text = text.replace(anchor, block + anchor, 1)
    old_debt = "Block Q remains intentionally deferred: an old in-flight onboarding snapshot created before `run-inputs.json` existed can lose a formerly owner-selected Source during reset/recreation. Fresh/current onboarding already persists and reuses owner-selected Sources correctly. Do not reopen the completed real placement merely to repair that legacy migration edge."
    new_debt = "The former Block Q owner-Source recovery debt is no longer deferred. The project owner's supplied real machine state proves the choice can be completely absent from legacy machine state; Block S step 3 now owns a safe explicit recovery/re-adoption path. Fresh/current onboarding already persists owner-selected Sources correctly."
    if old_debt not in text:
        raise SystemExit("PLAN deferred Block Q text missing")
    p.write_text(text.replace(old_debt, new_debt, 1), encoding="utf-8")


def complete() -> None:
    replace_once(
        "PLAN.md",
        "**Status: ACTIVE — step 2 of 4.**",
        "**Status: ACTIVE — step 3 of 4.**",
    )
    replace_once(
        "PLAN.md",
        "- [ ] 2. Remove package identity feedback from old generated Resource links such as `SECURITY.md -> CONTEXT.md`; previous generated output must never affect a fresh compile.",
        "- [x] 2. Remove package identity feedback from old generated Resource links such as `SECURITY.md -> CONTEXT.md`; previous generated output must never affect a fresh compile.",
    )
    state = Path("STATE.md")
    state.write_text(
        state.read_text(encoding="utf-8").rstrip()
        + "\n\n## Latest Block S real machine-state resource determinism checkpoint\n\n"
        + "The project owner's current `ai-workstation` machine snapshot exposed a compiler-0.4 package feedback loop: an exact Topic Resource (`SECURITY.md`) linked to generated `CONTEXT.md`, so resource closure copied whichever generated Official Context happened to exist and then followed its `CONTEXT.src.md` edit link. The placement acceptance therefore recorded a different root package digest from the package actually written by the same Step-9 journal even though normalized semantics and `CONTEXT.src.md` bytes agreed. Compiler 0.5 now treats a Markdown closure link to its owning Node's generated `CONTEXT.md` as a deterministic package-local bridge to the package's top-level Official Context. It never reads previous generated bytes, preserves the exact authored Resource bytes and link shape, avoids copying `CONTEXT.src.md` merely through generated output, and lets normal output cleanup remove the old compiler-0.4 copy. A regression reproduces the stale generated-context/resource-tree shape and proves first-build/second-build package identity plus zero drift. Block S proceeds to explicit recovery/re-adoption of the lost legacy Development Workflow owner Source.\n",
        encoding="utf-8",
    )


def apply() -> None:
    patch_compiler()
    patch_tests()
    patch_plan()


if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == "--complete":
        complete()
    elif len(sys.argv) == 1:
        apply()
    else:
        raise SystemExit("usage: _block_s_machine_state_step2.py [--complete]")
