from pathlib import Path

helper = Path("tools/_block_r6_source_step2.py")
text = helper.read_text(encoding="utf-8")
old = '''    replace_once(\n        "src/contextcanon/sources.py",\n        \'\'\'                elif key not in {"normalized-digest", "package-digest"}:\\n                    updated.append((key, value))\\n\'\'\',\n        \'\'\'                elif key == "ref" and accepted_ref is not None and re.fullmatch(r"[0-9a-f]{40}", value):\\n                    updated.append((key, accepted_ref))\\n                elif key not in {"normalized-digest", "package-digest"}:\\n                    updated.append((key, value))\\n\'\'\',\n    )\n'''
new = '''    p = Path("src/contextcanon/sources.py")\n    source_text = p.read_text(encoding="utf-8")\n    function_start = source_text.find("def _write_source_pin(")\n    function_end = source_text.find("\\n\\ndef _atomic_write_text", function_start)\n    if function_start < 0 or function_end < 0:\n        raise SystemExit("Source pin function boundary missing")\n    function = source_text[function_start:function_end]\n    old_branch = \'\'\'                elif key not in {"normalized-digest", "package-digest"}:\\n                    updated.append((key, value))\\n\'\'\'\n    new_branch = \'\'\'                elif key == "ref" and accepted_ref is not None and re.fullmatch(r"[0-9a-f]{40}", value):\\n                    updated.append((key, accepted_ref))\\n                elif key not in {"normalized-digest", "package-digest"}:\\n                    updated.append((key, value))\\n\'\'\'\n    if function.count(old_branch) != 1:\n        raise SystemExit(f"Source pin branch count {function.count(old_branch)}")\n    function = function.replace(old_branch, new_branch, 1)\n    p.write_text(source_text[:function_start] + function + source_text[function_end:], encoding="utf-8")\n'''
if text.count(old) != 1:
    raise SystemExit(f"R6 step2 helper patch call count {text.count(old)}")
helper.write_text(text.replace(old, new, 1), encoding="utf-8")
